# Main Script Settings
main:
  run_dir: ./models/tokenizer  # directory to save checkpoints and logs
  gpus: 1                      # number of GPUs to use (0 = CPU)
  precision: 32                # precision level (16 or 32)
  deterministic: True          # enable deterministic training
  seed: 813                    # random seed
  checkpoint: null             # path to a pre-trained model checkpoint

# Dataset Settings
data_config:
  data_dir: /well/win-camcan/shared/spring23/src  # directory containing data to use
  sampling_frequency: 250                         # unit: Hz

# Tokenizer Settings
model_config:

  # Meta data
  name: ephys_tokenizer

  # Model config
  n_channels: 52
  n_tokens: 128
  rnn_n_units: 128
  sequence_length: 200
  token_dim: 10
  token_kernel_padding: causal

  # Training config
  training:
    batch_size: 32
    n_epochs: 40
    optimizer:
      learning_rate: 1.0e-05
    multi_gpu: False

  # Callback config
  callback:
    temperature_annealing:
      n_annealing_epochs: 40
      n_stages: 40
